# Generated by Django 3.1.7 on 2021-06-15 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comercio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='carrito',
            name='comprar',
            field=models.BooleanField(default=False),
        ),
    ]
